# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 73f422df0a910986d8846eea5dd1ae3141c9a37cbe0a70eab9767316f1f1f2b22166e0a3ecdb3d38fbb86ed676e76b45869dd84ac845fe3d101074f1fe7d328e

test:
  domain_name: example.com 
  secret_key_base: b0f2b7fe5a20587a85bb4ce352697e80a414c7060cfde7a8daca237c89134697d5d399bdfdd4e663cb8d94d5cc6860ad482a4722478009ab0a6a7d7f6246c441

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
